=== BrianEnigma/puzzled_pint_archives/month.dtd
<!ELEMENT PPMonth (year,month,title,notes?,location,puzzle+,allPuzzles?,answerSheet*,answerSheetSolution?)>

<!ELEMENT year (#PCDATA)>      <!-- 4-digit year, e.g. 2015 -->
<!ELEMENT month (#PCDATA)>     <!-- 2-digit month, e.g. 02 -->

<!ELEMENT title (#PCDATA)>     <!-- Theme/Title for the month, e.g. The Big Lebowski -->

<!ELEMENT notes (#PCDATA)>     <!-- Markdown with overall theme intro text and authorship information -->

<!ELEMENT location (puzzle,answerword)>
<!ELEMENT answerword (#PCDATA)>


<!ELEMENT puzzle (title,notes?,file?,hint*,solution)>
<!ELEMENT file EMPTY>
<!ATTLIST file href CDATA #IMPLIED>
<!ELEMENT hint (#PCDATA)>
<!ATTLIST hint href CDATA #IMPLIED>	<!-- Hints will be either/or: either containing text or linking to a PDF or other document -->
<!ELEMENT solution (#PCDATA)>
<!ATTLIST solution href CDATA #IMPLIED> <!-- Solution could have both text+href, for example a textual walkthrough plus a PDF solve, but is typically just an href to a solution document -->

<!ELEMENT allPuzzles EMPTY>
<!ATTLIST allPuzzles href CDATA #IMPLIED>

<!ELEMENT answerSheet (#PCDATA)>
<!ATTLIST answerSheet href CDATA #IMPLIED>

<!ELEMENT answerSheetSolution EMPTY>
<!ATTLIST answerSheetSolution href CDATA #IMPLIED>

=== BrianEnigma/puzzled_pint_archives/archives/2019/11/month.xml
<?xml version="1.0"?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2019</year>
	<month>11</month>
	<title>Music</title>
	<icon href="icon.png"/>
	<notes>Thank you to this month's author: Scott D. Farquhar (Baltimore, MD)

We've prepared a spoiler-free [sheet of musical terms](musical_terms.pdf) if you're not musically inclined.</notes>
	<location>
		<puzzle>
			<title>Choir Rehearsal</title>
			<file href="00-location.pdf"/>
			<hint>Have no fear - no music knowledge is nessesary</hint>
			<hint>Connect the dots</hint>
			<hint>Do the lines cross something?</hint>
			<hint>The solution is THE FOOD OF LOVE.</hint>
			<solution href="00-location-solution.pdf"/>
		</puzzle>
		<answerword>thefoodoflove</answerword>
	</location>

	<puzzle>
		<title>Too Much Triangle</title>
		<file href="01-triangle.pdf"/>
		<hint>There are many references to the number 3 (title, composer, etc.). This is important</hint>
		<hint>Use only every 3rd measure</hint>
		<hint>Only the notes matter, not the rests</hint>
		<hint>It's morse</hint>
		<solution href="01-triangle-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Music Arranging</title>
		<file href="02-music_arranging.pdf"/>
		<hint>Match up like type of notes.</hint>
		<hint>This should have made letters</hint>
		<hint>Order by length of note (use tip sheet if you need to)</hint>
		<solution href="02-music_arranging-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Lost and Disorganized Pianist</title>
		<file href="03-lost_and_disorganized_pianist.pdf"/>
		<hint>LEFT and RIGHT are very important.</hint>
		<hint>If the directions say LEFT, use the bottom staff, if it is says right, use top staff.</hint>
		<hint>LEFT and RIGHT use different encodings.</hint>
		<hint>RIGHT is Semaphore, LEFT is Braille</hint>
		<hint>Translated numbers tell you what measure to use.</hint>
		<hint>Order by the list on the bottom</hint>
		<solution href="03-lost_and_disorganized_pianist-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Jazz Witches</title>
		<file href="04-jazz_witches.pdf"/>
		<hint>3 types of encodings are used</hint>
		<hint>Encodes are Hexidecmial, binary, and decimal</hint>
		<hint>Order by the number on the measure</hint>
		<solution href="04-jazz_witches-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Grand Finale (meta puzzle)</title>
		<file href="05-meta.pdf"/>
		<hint>Take the note letter names for the notes that are connected by a musical tie.</hint>
		<hint>A BAD EGG</hint>
		<hint>Use Pi as 3.14159 and take those measure numbers from the original puzzle.</hint>
		<hint>REPEAT REPEAT</hint>
		<hint>Caesar shift from G (G Clef) and F (F Clef).</hint>
		<hint>LET'S POLKA</hint>
		<hint>Take the note letter names for the notes connected by a musical slur.</hint>
		<hint>FEED A BEE A CABBAGE</hint>
		<hint>Use Solfege to get the final answer</hint>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Music Crossword (bonus puzzle)</title>
		<file href="06-bonus.pdf"/>
		<solution href="06-bonus-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/archives/2017/11/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../../month.dtd">
<PPMonth>
	<year>2017</year>
	<month>11</month>
	<title>Charlie and the Chocolate Factory</title>
	<icon href="icon.png"/>
	<notes>
Thanks to St. Louis Puzzled Pint player Matthew Stern for writing all of this month's puzzles! And thanks to Chelsea Branson for co-authoring the location puzzle!
	</notes>
	<location>
		<puzzle>
			<title>The Golden Ticket</title>
			<file href="00-location.pdf"/>
			<hint>Find the path from the golden ticket to the gates.</hint>
			<hint>Every turn you make is at a junction of two streets (one numbered, one named).</hint>
			<hint>Use the numbered street to index into the named street.  1st Ave + Stardust Blvd = S.</hint>
			<hint>The solution is STICKY FINGERS.</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>stickyfingers</answerword>
	</location>

	<puzzle>
		<title>The Chocolate Room</title>
		<file href="01-chocolate_room.pdf"/>
		<hint>Once you solve each clue, do you notice something regarding "holes", "bridges", "rivers"?</hint>
		<hint>Find a path that starts at a "Start" that avoids words with holes and rivers while going over the "bridge"</hint>
		<hint>The first half of the path before the bridge says "Kickstarter - Roald Dahl Book Title Adjective about James Peach" which is GIANT</hint>
		<hint>Second half of the path says "Extra squares NATO Letters Vertically"</hint>
		<solution href="01-chocolate_room-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Inventing Room</title>
		<file href="02-inventing_room.pdf"/>
		<hint>Once all lines a drawn, look to the uncovered letters (i.e. no line drawn through them)</hint>
		<hint>Uncovered letters spell out "HIGHLIGHT SINGLE WIRES"</hint>
		<hint>Did those single lines create a shapes that might be of use or perhaps spell out something?</hint>
		<solution href="02-inventing_room-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Nut Room</title>
		<file href="03-nut_room.pdf"/>
		<hint>Each nut can be transformed into a new word with a ROT cipher. That new word should coorspond with the squirrel responses below.</hint>
		<hint>The quanity for each price deThescribes how many squirrels use the new word</hint>
		<hint>The error code is how many letters foward each word is shifted</hint>
		<hint>Convert the error codes to letters (12 = L)</hint>
		<solution href="03-nut_room-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Television Room</title>
		<file href="04-television_room.pdf"/>
		<hint>Each movie description descrives a popular movie with one letter changed in its title.</hint>
		<hint>The first movie is "Toy Stork"</hint>
		<hint>Take the changed letter and place it in the televisions below.</hint>
		<solution href="04-television_room-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Great Glass Elevator (meta puzzle)</title>
		<file href="05-meta.pdf"/>
		<hint>I wonder where I can find bugs from the other puzzles?</hint>
		<hint>The candies all have traits that should be familar from the other puzzles</hint>
		<hint>Draw lines from the candies to the bugs. What's left?</hint>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Oompa Loompas (bonus puzzle)</title>
		<file href="06-bonus.pdf"/>
		<hint>Look for the candies in the testimonies</hint>
		<hint>Well, you might not find the candies EXACTLY. Perhaps with an extra ingredient?</hint>
		<hint>Albert's testimony contains the candy "Nerds", but with an "e" added</hint>
		<hint>Take the added letter to get the solution</hint>
		<solution href="06-bonus-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2017/03/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2017</year>
	<month>03</month>
	<title>Alice in Wonderland</title>
	<notes>Thanks to Justin Melvin and Elizabeth French of Seattle Eastside Game Control for writing all this month's core puzzles!  Thanks to [Cathy Saxton](https://www.idleloop.com/puzzles/) (also Seattle Eastside Game Control) for writing this month's bonus puzzle.</notes>
	<location>
		<puzzle>
			<title>Down the Rabbit Hole</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>Daisy-Chain means you're connecting the words together in a chain.</hint>
			<hint>Start with putting "Hole" in the blanks after Rabbit.</hint>
			<hint>It's not a Hole Card from Poker that you're looking for, which other word would fit in the middle?</hint>
			<hint>Hints for all answers:

- Home for a bunny
- Three-ring binder user's gadget
- Frequent customer reward system
- Place for poker
- Ping-Pong
- Wimbleton footware
- Scuff remedy
- Finish
- Not quite grey
- Character from Alice in Wonderland</hint>
            <hint>Take the numbered entries in order.</hint>
            <hint>Partial Answer:

- Rabbit Hole
- Hole Punch
- Punch Card
- Card Table
- Table Tennis
- Tennis Shoe
- Shoe Polish
- Polish Off
- Off White
- White Rabbit</hint>
            <hint>The solution is DON'T BE LATE</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>dontbelate</answerword>
	</location>

	<puzzle>
		<title>Advice from a Caterpillar</title>
		<file href="01-Advice_from_a_Caterpillar-puzzle.pdf"/>
		<hint>The set of four words in each column have a connection, as represented by the column header question mark</hint>
		<hint>You are not changing the words in the word bank, only copying them into place</hint>
		<hint>Not all of the words in the word bank are full words, some are partial words</hint>
		<hint>What happened to Alice throughout the story when she ate or drank?</hint>
        <hint>PARTIAL ANSWER: HEADER 1: Small</hint>
        <hint>PARTIAL ANSWER: HEADER 2: Little</hint>
        <hint>PARTIAL ANSWER: HEADER 3: Short</hint>
        <hint>PARTIAL ANSWER: HEADER 4: Big</hint>
        <hint>PARTIAL ANSWER: HEADER 5: Super</hint>
        <hint>PARTIAL ANSWER: HEADER 6: Mega</hint>
        <hint>PARTIAL ANSWER: COLUMN 1Small-Minded, Small Talk, Small Potatoes, Small Print</hint>
        <hint>PARTIAL ANSWER: COLUMN 2: Little:Rascals, Finger, Lord Fauntleroy, Mermaid</hint>
        <hint>PARTIAL ANSWER: COLUMN 3: Short:Bread, Cut, Circuits, Changed</hint>
        <hint>PARTIAL ANSWER: COLUMN 4: Big: Bang, Shot, Cheese, Apple</hint>
        <hint>PARTIAL ANSWER: COLUMN 5: Supersonic, Superfluidity, Superhero, Supermodel</hint>
        <hint>PARTIAL ANSWER: COLUMN 6: Megalith, Megabyte, Megalodon, Megalomania</hint>
        <hint>Put all the indicated letters into a 5x3 grid then read left to right top to bottom.</hint>
        <hint>ANSWER: Little Alice Liddell</hint>
		<solution href="01-Advice_from_a_Caterpillar-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>A Mad Tea-Party</title>
		<file href="02-Mad_Tea_Party-puzzle.pdf"/>
        <hint>Filling in the grid is a straightforward logic puzzle with no tricks to it</hint>
        <hint>The column and row totals are the total number of O's in that row or column (characters that did sit in that seat)</hint>
        <hint>The Mad Hatter did not sit in the striped armchair</hint>
        <hint>The March Hair sat in the Side Chair</hint>
        <hint>PARTIAL ANSWER: COMPLETED GRID
        
```
                1 2 3 4 5 6 7 8 9 10 
Bill the Lizard o o o   o   o     o 
Alice                         o o
Mad Hatter      o       o       o 
March Hare      o o o     o o     o 
Dormouse          o   o o o   o o 
Duchess         o   o   o       o
```</hint>
        <hint>Notice in the flavor text the words "I feel"</hint>
        <hint>Notice the pattern of darker lines on the grid, making 2x3 sections</hint>
        <hint>ANSWER: Decode the Braille to obtain "Makes Notes" which is the answer to Carrol's famous query</hint>
		<solution href="02-Mad_Tea_Party-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Off With Her Head!</title>
		<file href="03-Off_With_Her_Head-puzzle.pdf"/>
        <hint>You have to draw lines between dots. The title of the puzzle is a big clue</hint>
        <hint>This is a beheadment puzzle. Take the first letter off the word on the left and connect it to the word on the right</hint>
        <hint>PARTIAL ANSWER: LEFT WORDS
            
- FLOCK
- SWORD
- EYES
- YAWNING
- HANGER
- ABUSES
- WEIGHT
- UNIT
- FAIR
- LICE
- AGREED</hint>
        <hint>Focus on the letters that were beheaded</hint>
        <hint>Put them in order by card rank.</hint>
        <hint>ANSWER: SHUFFLE AWAY</hint>
		<solution href="03-Off_With_Her_Head-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Lobster Quadrille</title>
		<file href="04-Lobster_Quad-puzzle.pdf"/>
        <hint>"The sound of the creatures"</hint>
        <hint>Add the sound of "fish" to complete each word, e.g. the first one is BENE'FISH'AL -> BENEFICIAL</hint>
        <hint>PARTIAL ANSWER: ALL WORDS

- Beneficial
- Elfish
- Artifical
- Uffish (look it up)
- Deficient
- Fishtail
- Standoffish
- Sufficient
- Official
- Selfish
- Afficionado
- Superficial
- Proficient</hint>
        <hint>FINAL ANSWER: Take the highlighted words to get BEAUTIFUL SOUP</hint>
		<solution href="04-Lobster_Quad-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Curiouser and Curiouser (meta puzzle)</title>
		<file href="05-curiouser_and_curiouser-puzzle.pdf"/>
        <hint>You need to cut out the grid and remake a 3x3 grid. Note, keep the numbers upright! No rotation necessary!</hint>
        <hint>Don't forget to use your puzzle answers! They will help you know which edges to connect</hint>
        <hint>Each edge is a synonym for one half of each puzzle answer.</hint>
        <hint>Connect those to the other half of each answer to make a 3x3 grid.</hint>
        <hint>CDEFGABC is the center tile's top edge</hint>
        <hint>PARTIAL ANSWER: CENTER TILE CONNECTIONS: TOP Fabricates</hint>
        <hint>PARTIAL ANSWER: CENTER TILE CONNECTIONS: RIGHT Elsewhere</hint>
        <hint>PARTIAL ANSWER: CENTER TILE CONNECTIONS: BOTTOM Gone</hint>
        <hint>PARTIAL ANSWER: CENTER TILE CONNECTIONS: LEFT Young</hint>
        <hint>Connect the dots to make a drawing</hint>
        <hint>It's a cat. Know any famous cats from Alice in Wonderland?</hint>
        <hint>ANSWER: Cheshire Cat</hint>
		<solution href="05-curiouser_and_curiouser-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Pi Day (bonus puzzle)</title>
		<file href="06-pi_day-puzzle.pdf"/>
        <hint>Word Chain Puzzle Answers:

- Cherry
- Peach
- Coconut Cream
- Rhubarb
- Strawberry
- Key Lime
- Pumpkin
- Pecan
- Apple</hint>            
        <hint>Word Search Puzzle: Replace the π in the search grid with the letters "pi"</hint>
        <hint>CLUE ANSWERS:
            
- Spider
- Spice
- Pushpin
- Typing
- Picture
- Cockpit
- Pita
- Tropical
- Bagpipes
- Scampi
- Toothpick
- Pupil
- Pint
- Typical</hint>
        <hint>REMAINING LETTERS: The remaining letters say: "Read letters on left side of the π"</hint>
        <hint>FINAL ANSWER: Happy Pi Day</hint>
        <hint>Sectioned Grid Puzzle Answers:

```
. . . P . .
. . . . . A
. S . . . .
. . . . T .
Y . . . . .

. . . . . G . .
O . . . . . . .
. . . . . . O .
. . D . . . . .
. . . . . . . N
. . . . E . . .
. S . . . . . .
. . . S . . . .
```</hint>
        <hint>PASTRY GOODNESS</hint>
		<solution href="06-pi_day-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2014/04/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2014</year>
	<month>4</month>
	<title>Mix Tape</title>
	<notes>
	</notes>
	<location>
		<puzzle>
			<title>Forest for the Trees</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>The labels for each row are:

- 11 SLANG TERMS FOR UNITED STATES CURRENCY
- 9 DEAD MUSICIANS
- 5 MEMBERS OF ONE DIRECTION</hint>
			<hint>The matching items in each row are:

- Bread, Cabbage, Cheddar, Clams, Dough, Lettuce, Bones, Smackers, Stacks, Fins, and Spondoolie.
- Duane Allman, Stevie Ray Vaughan, Hank Williams, Jimi Hendrix, Jerry Garcia, Buddy Holly, John Bonham, Jim Morrison, and Otis Redding.
- Harry, Zayn, Louis, Niall, and Liam.</hint>
			<hint>This grid can be divided into 2x3 sections, which should remind you of the braille symbols on the Puzzled Pint Code Sheet.

The final answer is a 10-letter proper name.</hint>
			<hint>The solution is: TIMBERLAKE</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>timberlake</answerword>
	</location>

	<puzzle>
		<title>Rapper's Delight</title>
		<file href="01-rappers_delight-puzzle.pdf"/>
		<solution href="01-rappers_delight-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Cut Here</title>
		<file href="02-cut_here-puzzle.pdf"/>
        <hint href="02-cut_here-hints.txt"/>
		<solution href="02-cut_here-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Stuck in the Middle with You</title>
		<file href="03-middle-puzzle.pdf"/>
        <hint href="03-middle-hints.txt"/>
		<solution href="03-middle-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Cover Me</title>
		<file href="04-cover_me-puzzle.pdf"/>
		<solution href="04-cover_me-puzzle.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Song Remains the Same (US variant, Bonus Puzzle)</title>
		<file href="05-song_US-puzzle.pdf"/>
		<solution href="05-song_US-solution.pdf"/>
	</puzzle>
    
	<puzzle>
		<title>The Song Remains the Same (UK variant, Bonus Puzzle)</title>
		<file href="05-song_UK-puzzle.pdf"/>
		<solution href="05-song_UK-solution.pdf"/>
	</puzzle>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2015/04/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2015</year>
	<month>4</month>
	<title>The A-Team</title>
	<icon href="icon.png"/>
	<notes>[Dossiers](dossiers.pdf) are needed to solve main 4 puzzles - each team received one at event and needed to share.
        
Thanks to Wil Zambole of [Chicago Puzzled Pint](https://twitter.com/puzzpintchi) for writing all of this month's puzzles!
	</notes>
	<location>
		<puzzle>
			<title>Hire the A-Team</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>Each item shown is associated with a different country.</hint>
			<hint>How can you connect each country to its item?</hint>
			<hint>Does the phrase "English Bulldog" give you any ideas?</hint>		
			<hint>The phrases you make will form a chain. Keep track of the ordinal number of each country (first, second, etc.), then take that letter from the group.</hint>
            <hint>The first letter to grab is H from the starting country, FRANCE.</hint>
            <hint>First connection is FRENCH KISS.</hint>
            <hint>Last connection is SWISS BANK.</hint>
			<hint>The solution is HIDING.</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>hiding</answerword>
	</location>
	
	<puzzle>
		<title>Hannibal</title>
		<file href="01-hannibal-puzzle.pdf"/>
		<hint>There are 11 groups of 4.</hint>
		<hint>One in each group has been changed. Determine how it changed, and what it should be3.</hint>
		<hint>There are hints on file cards for groupings if you can't find them.</hint>
		<solution href="01-hannibal-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Face</title>
		<file href="02-face-puzzle.pdf"/>
		<hint>Face is second in command.</hint>
		<hint>Try reading downwards</hint>
		<hint>Follow the instruction, then look again somewhere else.</hint>
		<hint>The flowers are located on the file cards.</hint>
		<solution href="02-face-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>BA Baracus</title>
		<file href="03-ba-puzzle.pdf"/>
		<hint>Each of those clue answer has something in common about them.</hint>
		<hint>That connection has to do with the fact that his name is BA.</hint>
		<hint>Each clue leads to a person with two initials.</hint>
		<hint>Find those intitials in the grid, there is a letter in between each of them.</hint>
		<solution href="03-ba-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Murdoch</title>
		<file href="04-murdoch-puzzle.pdf"/>
		<hint>You will need help to get the rest of the map.</hint>
		<hint>Did you check the file cards?</hint>
		<hint>Find the most direct route.</hint>
		<hint>Try working backwards like a typical pencil maze would.</hint>
		<solution href="04-murdoch-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Mission Accomplished! (meta puzzle)</title>
		<file href="05-mission_accomplished-puzzle.pdf"/>
		<hint>The names on the bottom are in that order for a reason.</hint>
		<hint>What did you hear?</hint>
		<hint>After peforming the instruction, literally close the book.</hint>
		<solution href="05-mission_accomplished-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Fugitives (bonus puzzle)</title>
		<file href="06-figitives-puzzle.pdf"/>
		<hint>Each word on the left matches with one on the right.</hint>
		<hint>Find the missing word that would connect them</hint>
		<hint>See the plan through the jail cell bars.</hint>
        <solution href="06-figitives-solution.pdf"/>
	</puzzle>
	
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2015/05/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2015</year>
	<month>5</month>
	<title>Ex Machina</title>
	<notes>Puzzles adapted from the hunt on [JoCo Cruise Crazy 5](http://www.jonathancoulton.com/wiki/JoCo_Cruise_Crazy/JoCo_Cruise_Crazy_5).  Individual authors noted on each puzzle.  As always, a big thanks to our authors!
	</notes>
	<location>
		<puzzle>
			<title>Knock Knock</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>Identify the pictures on the left, then draw a straight line to connect each of those words with the appropriate response on the right. Keep in mind that every connection will be in the form of a [knock-knock joke](https://en.wikipedia.org/wiki/Knock-knock_joke)!

For example, the second picture on the left shows some *FIGS*. That connects with the first response on the right: "Fix the doorbell, it's broken!"</hint>
			<hint>The words for all the pictures on the left are:

- CASH
- FIGS
- TANK
- DOUGHNUT
- POLICE
- LETTUCE
- [DEWEY](https://en.wikipedia.org/wiki/Huey,_Dewey,_and_Louie)
- ORANGE
- GOAT</hint>
			<hint>The complete list of connections is:

- CASH - Cash who? ("cashew") - I always knew you were a nut!
- FIGS -- Fix the doorbell, it's broken!
- TANK - Tank who? ("thank you") - You're welcome!
- DOUGHNUT -- Do not ask, it's a secret.
- POLICE -- Please may I come in?
- LETTUCE -- Let us in, we're freezing.
- [DEWEY](https://en.wikipedia.org/wiki/Huey,_Dewey,_and_Louie) -- Do we have to keep telling silly jokes.
- ORANGE -- Aren't you glad I'm here?
- GOAT -- Go to the door and find out.</hint>		
			<hint>Solution displayed to the player</hint>
			<solution>Look at the lines you drew to connect each pair of dots. There should be five letters at line intersections, and when read top to bottom they spell: CANOE ("Can you come out and play?")</solution>
		</puzzle>
		<answerword>canoe</answerword>
	</location>
	
	<puzzle>
		<title>The Name of the Wind</title>
		<file href="01-name_of_the_wind-puzzle.pdf"/>
		<solution href="01-name_of_the_wind-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Ethics Subroutine</title>
		<file href="02-ethics_subroutine-puzzle.pdf"/>
		<hint href="02-ethics_subroutine-hint1.pdf"/>
		<solution href="02-ethics_subroutine-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Text Compression</title>
		<file href="03-text_compression-puzzle.pdf"/>
		<solution href="03-text_compression-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>You Know What They Say</title>
		<file href="04-you_know_what_they_say-puzzle.pdf"/>
        <hint href="04-you_know_what_they_say-hint1.pdf"/>
		<solution href="04-you_know_what_they_say-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Make Effort To Assemble (meta puzzle)</title>
        <notes>The completed answer sheet is required to solve this puzzle.</notes>
		<file href="05-make_an_effort_to_assemble-puzzle.pdf"/>
		<solution href="05-make_an_effort_to_assemble-solution.txt"/>
	</puzzle>
	
	<puzzle>
		<title>Fifty Shades of Array (bonus puzzle)</title>
		<file href="06-fifty_shades_of_array-puzzle.pdf"/>
		<solution href="06-fifty_shades_of_array-solution.pdf"/>
	</puzzle>
	
    <allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2018/08/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2018</year>
	<month>08</month>
	<title>Pok√©mon</title>
	<notes>
Thank you to this month's authors, Steven (Mobile, AL) and Zack (Atlanta, GA)

PM: Jen Dumont
	</notes>
	<location>
		<puzzle>
			<title>Like No One Ever Was </title>
			<file href="00-location.pdf"/>
			<hint>Solution displayed to the player</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>verybest</answerword>
	</location>

	<puzzle>
		<title>Tutorial Crossing</title>
		<file href="01-tutorial_crossing.pdf"/>
		<solution href="01-tutorial_crossing-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Clearing the Way</title>
		<file href="02-clearing_the_way.pdf"/>
		<solution href="02-clearing_the_way-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Name Rater</title>
		<file href="03-name_rater.pdf"/>
		<solution href="03-name_rater-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Hitting the Gym</title>
		<file href="04-hitting_the_gym.pdf"/>
		<solution href="04-hitting_the_gym-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Route to Victory (meta puzzle)</title>
		<file href="05-meta.pdf"/>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Missing House Keys (bonus puzzle 1)</title>
		<file href="06-bonus1.pdf"/>
		<solution href="06-bonus1-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Smell Ya Later! (bonus puzzle 2)</title>
		<file href="07-bonus2.pdf"/>
		<solution href="07-bonus2-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2012/05/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2012</year>
	<month>5</month>
	<title>National Water Safety Month</title>
	<icon href="icon.png"/>
	<notes>
	</notes>
	<location>
		<puzzle>
			<title>Covers</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>Did you notice the numbers on each image?  Maybe you should track down these albums.</hint>
			<hint>Artists and albums:

- Hall and Oates - Change of Season
- James Horner - Titanic: Music from the Motion Picture
- Bobby Darin - That's All
- Katrina and the Waves - Walking On Sunshine
- Billy Ocean - Suddenly
- Beach Boys - Still Cruisin'
- Enya - Watermark
- Doobie Brothers - What Were Once Vices Are Now Habits
- Billy Joel - Storm Front
- Muddy Waters - The Real Folk Blues</hint>
			<hint>Track names:

- Heavy Rain
- Unable to Stay, Unwilling to Leave
- Beyond the Sea
- Brown Eyed Son
- If I Should Lose You
- Kokomo
- Exile
- Black Water
- And So It Goes
- Rollin' and Tumblin'</hint>
			<hint>The solution is HOPWORKS BIKE BAR</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>hopworksbikebar</answerword>
	</location>

	<puzzle>
		<title>Flag</title>
		<file href="01-flag-puzzle.pdf"/>
		<hint href="01-flag-hint1.pdf" />
		<solution href="01-flag-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Shuffleboard</title>
		<file href="02-shuffleboard-puzzle.pdf"/>
		<solution href="02-shuffleboard-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>CrossWordSearch</title>
		<file href="03-crosswordsearch-puzzle.pdf"/>
		<solution href="03-crosswordsearch-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Whirlpool</title>
		<file href="04-whirlpool-puzzle.pdf"/>
		<solution href="04-whirlpool-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Treasure (meta puzzle)</title>
		<file href="05-treasure-puzzle.pdf"/>
		<solution href="05-treasure-solution.pdf"/>
	</puzzle>
    
    <answerSheet href="answersheet.pdf"/>
</PPMonth>
