=== BrianEnigma/puzzled_pint_archives/month.dtd
<!ELEMENT PPMonth (year,month,title,notes?,location,puzzle+,allPuzzles?,answerSheet*,answerSheetSolution?)>

<!ELEMENT year (#PCDATA)>      <!-- 4-digit year, e.g. 2015 -->
<!ELEMENT month (#PCDATA)>     <!-- 2-digit month, e.g. 02 -->

<!ELEMENT title (#PCDATA)>     <!-- Theme/Title for the month, e.g. The Big Lebowski -->

<!ELEMENT notes (#PCDATA)>     <!-- Markdown with overall theme intro text and authorship information -->

<!ELEMENT location (puzzle,answerword)>
<!ELEMENT answerword (#PCDATA)>


<!ELEMENT puzzle (title,notes?,file?,hint*,solution)>
<!ELEMENT file EMPTY>
<!ATTLIST file href CDATA #IMPLIED>
<!ELEMENT hint (#PCDATA)>
<!ATTLIST hint href CDATA #IMPLIED>	<!-- Hints will be either/or: either containing text or linking to a PDF or other document -->
<!ELEMENT solution (#PCDATA)>
<!ATTLIST solution href CDATA #IMPLIED> <!-- Solution could have both text+href, for example a textual walkthrough plus a PDF solve, but is typically just an href to a solution document -->

<!ELEMENT allPuzzles EMPTY>
<!ATTLIST allPuzzles href CDATA #IMPLIED>

<!ELEMENT answerSheet (#PCDATA)>
<!ATTLIST answerSheet href CDATA #IMPLIED>

<!ELEMENT answerSheetSolution EMPTY>
<!ATTLIST answerSheetSolution href CDATA #IMPLIED>

=== BrianEnigma/puzzled_pint_archives/archives/2018/12/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../../month.dtd">
<PPMonth>
	<year>2018</year>
	<month>12</month>
	<title>The Nightmare Before Christmas</title>
	<icon href="icon.png"/>
	<notes>
Thank you to this month's author: Leanna Lewis (Sydney, Australia)

Bonus puzzle by: Neal Tibrewala (Austin, TX)

Editor: Jen Dumont (Portland, OR)
	</notes>
	<location>
		<puzzle>
			<title>Holiday Doors</title>
			<file href="00-location.pdf"/>
			<hint>The riddle allows for you to eliminate the doors until 1 remains.</hint>
			<hint>The numbers on the doors are used as an index into the name of the town on the door.</hint>
			<hint>1= H, 5 = O, 6 = W, 3 = L</hint>
			<hint>The solution is HOWL</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>howl</answerword>
	</location>

	<puzzle>
		<title>Making Christmas</title>
		<file href="01-making_christmas.pdf"/>
		<hint>This is a battleships puzzle, but with toys instead of ships.</hint>
		<hint>The train takes 4 spaces, dolls 3, boats 2 and balls 1.</hint>
		<hint>Using the numbers on each axis, place the toys in the correct spaces with none in adjacent spaces to each other (none of them touching!). The toys are given in the correct orientation as a clue.</hint>
		<hint>Note the flavour "Anchors Away!", all of the cells containing the anchor spells out the answer if you read it in the usual order.</hint>
           		<solution href="01-making_christmas-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Mayor's Christmas Countdown</title>
		<file href="02-mayors_countdown.pdf"/>
		<hint>This is a binary puzzle, however is not an equal sized grid on both sides like most others.</hint>
		<hint>Use the provided numbers as a start to fill in the rest of the gird, ensuring that there are no more than two 0’s and two 1’s horizontally or vertically next to each other.</hint>
		<hint>Then use the shaded squares to decifer the binery message reading each line separately downwards, reading each column from left to right.</hint>
		<hint>ONE MINUS ONE</hint>
		<solution href="02-mayors_countdown-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Oogie Boogie's Gamble</title>
		<file href="03-oogie_gamble.pdf"/>
		<hint>Complete the crossword clues, the beginning and end of each answer is listed at the bottom as a hint.</hint>
		<hint>The part missing in each word clues to help find which dice go with which clue.</hint>
		<hint>Look and see in the flavor text is hinting braille.</hint>
		<hint>The substring in each word, corresponds to the number of dots on each dice which are put together to spell out a word in braille.</hint>
		<solution href="03-oogie_gamble-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Sally's Patchwork</title>
		<file href="04-sallys_patchwork.pdf"/>
		<hint>This is a Magic Square puzzle, hinted by magic and square in the flavour text and 87 being what every row adds up to.</hint>
		<hint>Cut out each of the patches, and use the starter segments to place the patches into the correct place so that each row (horizontally, vertically and diagonally) adds up to 87.</hint>
		<hint>Decode the Pigpen face, partial answer: NOT ALIVE</hint>
		<solution href="04-sallys_patchwork-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Spiral Hill (meta)</title>
		<file href="05-meta.pdf"/>
		<hint>Place all of the previous answers in the incomplete words, to make completed thematic answers.</hint>
		<hint>Fill in the grid using the list of words.</hint>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Analogies (bonus / meta-meta)</title>
		<file href="06-bonus_meta_meta.pdf"/>
		<hint>Start by linking as many images as you can in column 1 with those in column 2. Likewise with those in 3 and 4.</hint>
		<hint>Now you can link the pairs together across the "As" in one of two ways, either by keeping the same Analogous relationship, or by matching elements belonging to the set themes.</hint>
		<hint>'AS' PAIRING HINTS:

- Baseball is a game, mostly played where?
- For what non-cleaning task can a broom be used, and by whom? What do you decorate at Christmas?
- Have you looked up the meanings of those idioms?
- Shift-1 vs Shift-7?
- That Pikachu and Ash wearing a Pokemon hat!
- The internet is necessary for which month's theme?
- The ring is a Stargate
- What's another name for a maze?
- Where can you find animals?
- Which role-playing game was featured in the show?
- Who painted the Mona Lisa?</hint>
		<hint>LIST OF ANALOGIES USED:

- Action : Thing Acted Upon
- Definition : Animal Idiom
- Malicious Intent : Mechanism to Achieve It Member : Writing-based Set
- Peer : Peer in the same category
- PigPen : English
- Place : Action
- Reverse thing : Thing
- Specific Instance : Category
- Temporal Part : Whole
- Tool : Activity
- Word : Two-Word Anagram</hint>
		<hint>Note the + and Equal signs. This will help you to fill in the __ . before each meta answer</hint>
		<hint>Sum the two numbers from the pair on the left of the equals, then subtract the one number you have from its corresponding pair to the right of the equals, this give the missing number.</hint>
		<hint>Index each meta answer by the number you found to get the final answer.</hint>
		<solution href="06-bonus_meta_meta-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2010/08/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2015</year>
	<month>8</month>
	<title>Food</title>
	<notes>
	</notes>
	<location>
		<puzzle>
			<title>Don't Panic</title>
            <notes>Milliways is known throughout the galaxy as a great place to get a meal while watching the universe end all around you. Five friends, Beeblebrox, Dent, Marvin, Prefect, and Trillian stopped by to grab a bite. Each brought with them an essential travel item (face flannel, gnat spray, a space suit, a towel and wet weather gear), ordered a different dish (fairy cake, flank steak, Ameglian Major Cow, peanuts, and sandwiches), and ordered a different drink (Gargleblaster, Gee-N-N-Tâ€™N-ix, Jinond-o-nicks, Jynnantonnyx, and a drink from the Nutri-matic). Can you deduce from the given clues which friend ordered which meal and drink, brought which item, and the order in which they arrived at Milliways?</notes>
			<file href="00-location-puzzle.pdf"/>
			<hint>Numbers are sometimes used for indexing letters. Indexing the number 5 into the word PETUNIA produces the 5th letter, N.</hint>
            <hint>Dinners:
                
- Flank Steak
- Ameglian
- Fairy Cake
- Peanuts
- Sandwiches</hint>
            <hint>Items:

- Face Flannel
- Space Suit
- Gnat Spray
- Towel
- Wet Weather Gear</hint>
            <hint>Characters:
                
- Trillian
- Dent
- Marvin
- Prefect
- Beeblebrox</hint>
            <hint>Drinks:
                
- Jynnantonnyx
- Jinond-o-nicks
- Gargleblaster
- Nutri-matic
- Gee-N-N-T'N-ix</hint>
            <hint>The solution is NEPO</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>nepo</answerword>
	</location>
	
	<puzzle>
		<title>Puzzled Pint Dinner</title>
        <notes>Print this file double-sided.</notes>
		<file href="01-puzzled_pint_diner-puzzle.pdf"/>
		<solution href="01-puzzled_pint_diner-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Hipster Care Package</title>
		<file href="02-hipster_care_package-puzzle.pdf"/>
		<solution href="02-hipster_care_package-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Hurt Feelings</title>
		<file href="03-hurt_feelings-puzzle.pdf"/>
		<solution href="03-hurt_feelings-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Roasted Vegetables</title>
		<file href="04-roasted_vegetables-puzzle.pdf"/>
		<solution href="04-roasted_vegetables-solution.pdf"/>
	</puzzle>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2017/06/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2017</year>
	<month>6</month>
	<title>The Prisoner</title>
	<notes>Thanks to [E &amp; S Lindstrom](https://twitter.com/Eric_Lindstrom) of San Francisco for writing this month's set!</notes>
	<location>
		<puzzle>
			<title>Welcome</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>It's a word search: scratch out the deer names that are strung together in the line at the bottom.</hint>
			<hint>The deer are: sika, marsh, red, fallow, mule, rusa, rein, tufted, roe, and brocket</hint>
			<hint>Read the remaining letters not used by words in the bank.</hint>
			<hint>The solution is COME TO THE GREEN DOME</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>cometothegreendome</answerword>
	</location>

	<puzzle>
		<title>International Cheat Sheet</title>
        <notes>This is NOT A PUZZLE. It holds useful idioms and words for non-Americans</notes>
		<file href="InternationalCheatSheet.pdf"/>
		<solution href="InternationalCheatSheet.pdf"/>
	</puzzle>

	<puzzle>
		<title>Telephone</title>
		<file href="01-telephone-puzzle.pdf"/>
        <hint>the number of slots at the top of the switchboard wiring diagram is equal to the number of digits in the “international phone number” provided</hint>
        <hint>the funnel lines below the slots imply that what goes into each of the eight empty boxes is determined by three digits above</hint>
        <hint>each three digit set has a five in the middle, just like the phone pad shown, where all digits also connect to the five in the center</hint>
        <hint>each three digit set makes semaphore on the phone pad</hint>
        <hint>the eight letters for the empty boxes are: o, s, n, l, l, a, c, y</hint>
        <hint>follow the cables to populate the final message with those letters, sometimes in more than one place</hint>
		<solution href="01-telephone-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Walk on the Grass</title>
		<file href="02-walk_on_the_grass-puzzle.pdf"/>
        <hint>each sentence describes a number in some way</hint>
        <hint>the number is an index for that sentence – count in that number of letters to get the letter for that sentence</hint>
        <hint>USEFUL IDIOMS (PARTIAL ANSWERS)
    
- There are 7 Deadly Sins
- Snow White knows 7 dwarves
- 2's Company, but 3's a crowd
- There are 3 Blind Mice in the famous children's song
- If you're "living on cloud 9", you're very happy
- The old addage about proactivity is "a stitch in time saves 9"
- Cats are said to have 9 lives, so how many ressurections is that?
- Due to standard burial depth, dead people are said to be "6 feet under"
- Finding a 4-leafed clover is said to bring good luck</hint>
		<solution href="02-walk_on_the_grass-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>A Still Tongue</title>
		<file href="03-still_tongue-puzzle.pdf"/>
        <hint>start at the upper left circle with “hook” and “crook” and think about what these words share, do not share, and how this relates to the bottom image in their circle</hint>
        <hint>in each circle, upper right words have five letters; upper left and bottom words have four; remove letters that the upper words have in common, and the remaining three, plus one you must add, make a word that describes the bottom image; e.g. Hook – CRook + I = RICH</hint>
        <hint>use solved circles to tell you what words to use for pictures in unsolved circles and continue the process for all the circles; e.g., when you solve Hook – Crook = RICH, look for the other circle with the RICH picture in the upper left and solve that one next, and so on</hint>
        <hint>ROW 1 PICTURES
            
- Hook, Crook, Rich
- Trap, Earth, Hemp
- Tuna, Acute, Cane</hint>
        <hint>ROW 2 PICTURES
        Tail, Liter, Fear

- Hemp, Peach, Camo
- Cane, Ranch, Hero
- Rich, Chart, Tail</hint>
        <hint>ROW 3 PICTURES

- Camo, March, Horn
- Hero, Store, Shot
- Fear, Ferry, Tray</hint>
        <hint>ROW 4 PICTURES

- Horn, Phone, Pear
- Shot, Chest, Core
- Tray, Party, Trap
- Pear, Prune, Tuna</hint>
        <hint>look at the letters you need to add to make bottom words, reading left to right, top to bottom</hint>
		<solution href="03-still_tongue-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Questions</title>
		<file href="04-questions-puzzle.pdf"/>
        <hint>the “what” questions are in pairs – connected by “and” – where both have the same seven-letter answer</hint>
        <hint>PARTIAL ANSWER: ALL 15 ANSWERS soluble, nosejob, inquiry, sidearm, inertia, station, saffron, diamond, exhaust, cricket, bishops, capital, burning, affairs, incense</hint>
        <hint>the letters in the circles spell, left to right, top to bottom, the word “squares”</hint>
        <hint>mark all letters tagged with a number that’s a perfect square</hint>
        <hint>the marked “square” letters string along in the shape of a question mark – read these letters along the direction of writing that mark</hint>
		<solution href="04-questions-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>It Can Be Done (Meta Puzzle)</title>
		<file href="05-meta-puzzle.pdf"/>
        <hint>Follow the example, filling in the 3 choices for each shape into the boxes.</hint>
        <hint>Each letter of the answer's blanks are a choice of three, find English words and figure out where the spaces are to solve this</hint>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Humour (Bonus Puzzle)</title>
		<file href="06-bonus-puzzle.pdf"/>
        <hint>All the quotes are slightly wrong</hint>
        <hint>fix the incorrect word in each quote, then read the correct words from top to bottom, and do the same with the incorrect words</hint>
        <hint>CORRECT WORDS I got your number I need to make you mine Jenny</hint>
        <hint>INCORRECT WORDS white letters case sensitive phone number indicates which used for Gramogram</hint>
        <hint>LEFT BLANKS the Jenny quote implies the phone number: 8 7 6 5 3 0 9</hint>
        <hint>each quote has a white letter on black – instead of writing the phone number, write the case sensitive white letter from the quote of that number; e.g., instead of “eight” write a capital B because quote number eight highlights that letter</hint>
        <hint>CENTER BLANKS on the underscores at the bottom, you get the gramogram: BeC-ingU</hint>
		<solution href="06-bonus-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/archives/2013/05/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2013</year>
	<month>5</month>
	<title>Arrested Development</title>
	<icon href="icon.png"/>
	<notes>
	</notes>
	<location>
		<puzzle>
			<title>Title Here</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>Did you notice that it is a PIG PEN cipher?</hint>
			<hint>The first word decodes cleanly, but there's something about the rest that isn't quite right.</hint>
			<hint>Have you tried reorienting the symbols?</hint>
			<hint>Have you tried reorienting the symbols by using the time?</hint>
			<hint>Orient your paper so that the top of the page faces an analog clock's hour hand (90 degrees right for 3:00, 90 degrees left for 9:00, upside-down for 6:00, etc.)</hint>
			<hint>The message says: Prison break on Tuesday meet at Columbia River Brewing</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>columbiariverbrewing</answerword>
	</location>

	<puzzle>
		<title>Banana Stand</title>
		<file href="01-bananastand-puzzle.pdf"/>
		<solution href="01-bananastand-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Hashiwokakero</title>
		<file href="02-hashiwokakero-puzzle.pdf"/>
		<solution href="02-hashiwokakero-solution.txt"/>
	</puzzle>

	<puzzle>
		<title>Stair Car</title>
		<file href="03-staircar-puzzle.pdf"/>
        <hint href="03-staircar-grid.pdf"/>
		<solution href="03-staircar-puzzle.pdf"/>
	</puzzle>

	<puzzle>
		<title>White Collar Crimes</title>
		<file href="04-crimes-puzzle.pdf"/>
		<solution href="04-crimes-solution.pdf"/>
	</puzzle>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/archives/2020/03/month.xml
<?xml version="1.0"?>
<!DOCTYPE PPMonth SYSTEM "../../../month.dtd">
<PPMonth>
	<year>2020</year>
	<month>03</month>
	<title>Frankie &amp; Louie</title>
	<icon href="icon.png"/>
	<notes>Thank you to this month's author: Robert Becker (St. Louis, MO)</notes>
	<location>
		<puzzle>
			<title>Sin Laws Curb Limit</title>
			<notes>This month's location puzzles is an animated GIF loop.</notes>
			<file href="00-location.gif"/>
			<hint>Consider what letters are "exactly opposite" of each other on the dice.</hint>
			<hint>C=U Q=H B=Y M=V N=T J=D O=W P=X K=R I=E A=G F=Z S=L</hint>
			<hint>substituting each letter in "SIN LAWS CURB LIMIT" translates into "LETS GO LUCKY SEVEN"</hint>
			<hint>The solution is LETS GO LUCKY SEVEN</hint>
			<solution>View the hints to learn the solition.</solution>
		</puzzle>
		<answerword>letsgoluckyseven</answerword>
	</location>

	<puzzle>
		<title>Shooting Blanks</title>
		<file href="01-shooting_blanks.pdf"/>
		<hint>Connect the dots.</hint>
		<hint>What letters get crossed twice?</hint>
		<solution href="01-shooting_blanks-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Get-Away</title>
		<file href="02-the_getaway.pdf"/>
		<hint>What letters are on the cube?</hint>
		<hint>Start the cube with the correct letter facing up (corresponding to the path you are going to read).</hint>
		<hint>Take the south path (use N) and by rolling and shifting you should end up with "DECODE THIS".</hint>
		<hint>Do another shift on DECODE THIS to get your final answer.</hint>
		<solution href="02-the_getaway-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Downsizing the Gang</title>
		<file href="03-downsizing.pdf"/>
		<hint>The blanks should be filled with a word that completes compound words or phrases.</hint>
		<hint>The words are: BATH BOOT CASE GUEST NUT TAGS FLAT FLIGHT REAL OPERA RODS GRAPES</hint>
		<hint>Drop the common letters in each combined block. Repeat to get the final word. Use the numbers from the original entry for ordering.</hint>
		<solution href="03-downsizing-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Got It All Covered</title>
		<file href="04-covered.pdf"/>
		<hint>The correct numbers are: 1LU, 3RO, 6BU 1LO, 3LU, 4TU 4TO, 1LU, 3RU â€“ rotate 180* 6BU, 2RU 6BO, 2RU 6BO, 1LU, 3RU 4TU, 1LU, 3RU 1LO, 3LU, 6BU 3RU, 2RO, 6BO</hint>
		<solution href="04-covered-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Taking the Rap (meta puzzle)</title>
		<file href="05-meta.pdf"/>
		<hint>Frankie is a HOUND.</hint>
		<hint>Placing HOUND in the spaces 1-5 in the grid will lock ing the ordering of the previous answers.</hint>
		<hint>Read the 5th column from top to bottom.</hint>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Jack Flash Does Vegas (bonus puzzle)</title>
		<file href="06-bonus.pdf"/>
		<hint>"Suit line up" tells you that each of the 21s will connect via a straight line through their suits.</hint>
		<hint>Once you've drawn all the lines the picture may be slightly abstract, but should look like a person leaping over the road. This is a hint as to the answer.</hint>
		<solution href="06-bonus-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2017/01/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2017</year>
	<month>01</month>
	<title>Hamilton</title>
	<notes>Thanks to St. Louis Puzzled Pint player Matthew Stern for writing all of this month's main puzzles!  Thanks to [Curtis Chen](https://twitter.com/sparckl) (Puzzled Pint co-founder and Portland Game Control) for writing the bonus puzzle!</notes>
	<location>
		<puzzle>
			<title>Alexander Hamilton</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>Every four-line stanza describes a different well-known historical figure or celebrity. Web searching is encouraged; try combinations of quoted phrases, proper names, and any other unusual details.</hint>
			<hint>The people described are: Isaac Newton, Tony Hawk, Ernest Hemingway, Eric Idle, George Harrison, and Taylor Swift.</hint>
			<hint>Fill in the blanks with each person's first and last initials to spell out the final, 3-word answer.</hint>
			<hint>The solution is IN THE HEIGHTS.</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>intheheights</answerword>
	</location>

	<puzzle>
		<title>Guns and Ships</title>
		<file href="01-guns_and_ships-puzzle.pdf"/>
		<hint>FIVE(5) soldiers will end up adjacent to more than one object (tree, tent, flag, or cannon). Remember, diagonal does NOT count as adjacent!</hint>
		<hint>There are FOUR(4) soldiers in the third column from the right (labeled with letters EU-E-YO-E, top to bottom).</hint>
		<hint>There are THREE(3) soldiers in the top row (labeled TG-O-ME-E, left to right)</hint>
		<hint>There is only ONE(1) soldier in the bottom row, in square E to the left of the American tent and below the cannon.</hint>
        <hint>Using the blanks below the grid, break up the sequence of letters marked by the soldiers (TEE-EYE-EN-KAY-E-ARE), then sound them out as letters to spell a word: T-I-N-K-E-R</hint>
        <hint>Every British ship can be seen by at least two US ships.</hint>
        <hint>There are THREE(3) British ships in the third column from the right (labeled 3RLYDTEK4, top to bottom).</hint>
        <hint>There are TWO(2) British ships in the second row from the top (labeled QSOLOURZ3, left to right).</hint>
        <hint>The last TWO(2) British ships are in the far right column and the bottom row.</hint>
        <hint>Do the words TINKER and SOLDIER remind you of anything? Perhaps a 1974 spy novel by British author John le Carr√©, which was made into a 2011 film starring Gary Oldman?</hint>
        <hint>The answer is TAILOR SPY.</hint>
		<solution href="01-guns_and_ships-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Nonstop</title>
		<file href="02-nonstop-puzzle.pdf"/>
		<hint>Notice the bold words in the flavortext: flag and time. (Also the alarm-clock and human-with-arms icons in the corners of the "parchment.") Yup, it's everyone's favorite code: semaphore using analog clock hands!</hint>
		<hint>To start, only look at the times (7:50PM, 4:35PM, etc.) and translate those as semaphore letters.</hint>
		<hint>The semaphore spells: INDEX SUM OF MONTH DAY</hint>
		<hint>Now substitute the proper number for each month name, add that value to the day number, and use the result to index into the associated essay title. For example, the first line: 1+7=8 and the 8th letter is "I".</hint>
        <hint>The answer is: I NEED A RIGHT HAND MAN (but you only need the last three words for the meta).</hint>
		<solution href="02-nonstop-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>What'd I Miss?</title>
		<file href="03-whatd_i_miss-puzzle.pdf"/>
		<hint>Note the bold word miss in the flavortext: every crossword answer will include that sequence of four letters.</hint>
		<hint>Furthermore, when filling in the grid, all four letters "MISS" are crammed into a single cell. So the answer for 13-down is actually eight(8) letters long.</hint>
		<hint>MISSpoke, MISSissippi queen, reMISSion, eMISSary, MISSion impossible, MISS universe, interMISSion</hint>
		<hint>transMISSion, subMISSive, perMISSion, case disMISSed, MISSouri, little MISS muffet, lying by oMISSion, comMISSioner, MISSoula</hint>
        <hint>Once you've filled in the grid, take the letters from the cells labeled with round callouts in alphabetical order.</hint>
        <hint>The answer is PRIDE OF MT. VERNON.</hint>
		<solution href="03-whatd_i_miss-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>The Room Where It Happens</title>
		<file href="04-the_room-puzzle.pdf"/>
		<hint>Note the bold word in flavortext: initial. Only look at the first letters of the words in each speech bubble.</hint>
		<hint>Each person is saying something different. "James Madison's guiding words" tell you what to do: SHIFT STATES AND THEN REVERSE</hint>
		<hint>"Thomas Jefferson's stated claims (often abbreviated)" indicates you want the two-letter postal abbreviation for the states whose capital cities are named. The next hint is a reference sheet.</hint>
        <hint href="04-the_room-hint.pdf"/>
		<hint>"Hamilton's calculated comments" are numbers: ELEVEN, TWENTY-THREE, FIFTEEN, and ELEVEN.</hint>
		<hint>For each "table," take Jefferson's letter pair, shift the individual letters forward in the alphabet by Hamilton's number, then reverse the order of those two letters as Madison instructed. So "The Meeting" yields PA, shifted by 11 to AL, then reversed to LA</hint>
		<hint>The answer is LANCELOT.</hint>
		<solution href="04-the_room-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Who Lives, Who Dies, Who Tells Your Story (meta puzzle)</title>
		<file href="05-meta-puzzle.pdf"/>
		<hint>The first letters of the biographies spell out BOOK CIPHER. Fun fact: in musical theater, "book" means the lyrics of a show. Do you see Hamilton lyrics anywhere on the previous four puzzles?</hint>
		<hint>The bold words in the flavortext indicate a specific variety of book cipher: puzzle, quote line, word, and letter. Every sequence of four numbers will yield a single letter. Can you connect the icons on page 2 to four of the bios on page 1?</hint>
		<hint>The previous puzzle answers appear in the relevant biographies: Alexander Hamilton ("right hand man"), Marquis de Lafayette ("Lancelot"), Hercules Mulligan ("tailor...spy"), and George Washington ("pride of Mount Vernon"). On page 2, draw two lines for each man's "life path": from his birth decade to the puzzle referencing him, then from the puzzle icon to his death decade. For example, Hercules Mulligan goes from "1740-1749" to the top icon ("Guns and Ships") to "1820-1829". You'll end up with eight lines total.</hint>
		<hint>Each line segment crosses exactly four numbered scrolls. That book cipher uses the lyrics quoted inside the scrolls at the top of each puzzle. For example, Hercules Mulligan's first cipher is 4-3-2-1: puzzle #4 (The Room Where It Happens), 3rd line of quote ("We just assume that it happens"), 2nd word, 1st letter = J. Lather, rinse, repeat.</hint>
        <hint>The final answer is... JUST WAIT !</hint>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>A Rainbow Chorus (bonus puzzle)</title>
		<file href="06-bonus-puzzle.pdf"/>
		<solution href="06-bonus-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>
