=== BrianEnigma/puzzled_pint_archives/month.dtd
<!ELEMENT PPMonth (year,month,title,notes?,location,puzzle+,allPuzzles?,answerSheet*,answerSheetSolution?)>

<!ELEMENT year (#PCDATA)>      <!-- 4-digit year, e.g. 2015 -->
<!ELEMENT month (#PCDATA)>     <!-- 2-digit month, e.g. 02 -->

<!ELEMENT title (#PCDATA)>     <!-- Theme/Title for the month, e.g. The Big Lebowski -->

<!ELEMENT notes (#PCDATA)>     <!-- Markdown with overall theme intro text and authorship information -->

<!ELEMENT location (puzzle,answerword)>
<!ELEMENT answerword (#PCDATA)>


<!ELEMENT puzzle (title,notes?,file?,hint*,solution)>
<!ELEMENT file EMPTY>
<!ATTLIST file href CDATA #IMPLIED>
<!ELEMENT hint (#PCDATA)>
<!ATTLIST hint href CDATA #IMPLIED>	<!-- Hints will be either/or: either containing text or linking to a PDF or other document -->
<!ELEMENT solution (#PCDATA)>
<!ATTLIST solution href CDATA #IMPLIED> <!-- Solution could have both text+href, for example a textual walkthrough plus a PDF solve, but is typically just an href to a solution document -->

<!ELEMENT allPuzzles EMPTY>
<!ATTLIST allPuzzles href CDATA #IMPLIED>

<!ELEMENT answerSheet (#PCDATA)>
<!ATTLIST answerSheet href CDATA #IMPLIED>

<!ELEMENT answerSheetSolution EMPTY>
<!ATTLIST answerSheetSolution href CDATA #IMPLIED>

=== BrianEnigma/puzzled_pint_archives/archives/2018/02/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../../month.dtd">
<PPMonth>
	<year>2018</year>
	<month>02</month>
	<title>Stargate</title>
	<icon href="icon.png"/>
	<notes>
Thanks to Twin Cities player August H. for writing nearly all of this month's puzzles. And thanks to St. Louis player Robert B. for writing this month's bonus.

Editor: Jen Dumont
	</notes>
	<location>
		<puzzle>
			<title>The Message</title>
			<file href="00-location.pdf"/>
			<hint>Each piece has one member from 4 different ordered lists.</hint>
			<hint>The lists are Famous Scientists, Elements of the Periodic Table, Stars Near Earth, Pharohs of Egypt.</hint>
			<hint>List are order by Birthdate, Atomic Number, Distance from Earth and Reign.</hint>
			<hint>The solution is STARGATE BURIED AT GIZA</hint>
			<solution href="00-location-solution.txt" />
		</puzzle>
		<answerword>stargateburiedatgiza</answerword>
	</location>

	<puzzle>
		<title>Abydos</title>
		<file href="01-abydos.pdf"/>
		<hint>The dots are arrange very specifically such that you can create 7 straight lines</hint>
		<hint>Use the 7 glyphs on the second page. Notice that they show up twice.</hint>
		<hint>The pairs are semaphore</hint>
		<hint>Use number of dots in the lines created in step one to determine letter placement</hint>
		<solution href="01-abydos-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>P3X-179</title>
		<file href="02-p3x-179.pdf"/>
		<hint>Create the single path from the start to end with the pieces.</hint>
		<hint>What is left?</hint>
		<solution href="02-p3x-179-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Searching for Artifacts</title>
		<file href="03-searching_for_artifacts.pdf"/>
		<hint>Shaded letters are the first letter of each answer</hint>
		<hint>CROSS WORD ANSWERS: Ascend, Glyph, Jumper, Daedalus, Embarkation, Aurora, Atalantis, Chevron, Anubis</hint>
		<hint>What do you have left over?</hint>
		<solution href="03-searching_for_artifacts-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Thirteen Steps to Victory (meta puzzle)</title>
		<file href="04-bonus.pdf"/>
		<hint>You must use the other puzzles to solve!</hint>
		<hint>Place the puzzle answers in one of the grids</hint>
		<hint>Translate the ancient into another grid and then convert to letters some how</hint>
		<hint>The coversion is based on the puzzle the matching answer in the grid location is from.</hint>
		<hint>The first set, use Abyods and count around the 1st page stargate then put the symbol into the grid like you did when you originally solved that puzzle</hint>
		<hint>Second set use P3X-179 and use the grid coordinates</hint>
		<hint>Thrid set use Artifact</hint>
		<hint>It seems like there are errors? Or are those relevant? This grid is so nicely laid out for a certain encoding that use 2*3 blocks</hint>
		<hint>Using braille, use only the blocks where the letters match both the puzzle answers and the ancient translations</hint>
		<solution href="04-bonus-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Dynamic Duos (bonus puzzle)</title>
		<file href="05-meta.pdf"/>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/archives/2020/07/month.xml
<?xml version="1.0"?>
<!DOCTYPE PPMonth SYSTEM "../../../month.dtd">
<PPMonth>
	<year>2020</year>
	<month>07</month>
	<title>Puzzled Pint's 10th Anniversary</title>
	<icon href="icon.png"/>
	<notes>Thank you to this month's authors: Matthew Shields, Ana Roeszler, Bernard Sanders, Brian Enigma, Matt Cleinman, Jennifer Dumont, and Andrea Blumberg! (Portland, OR)
	</notes>
	<location>
		<puzzle>
			<title>Time Travel</title>
			<file href="00-location.pdf"/>
			<hint>Each of the clues describes a movie, or a television series.</hint>
			<hint>Use the beginning (first letter) of the title for each movie or TV show.

The titles are:

- Hot Tub Time Machine
- Planet of the Apes
- The Time Machine
- Bill and Ted's Excellent Adventure
- Doctor Strange
- Donnie Darko
- Midnight in Paris
- Doctor Who
- Groundhog Day</hint>
			<hint>Shift the first letter by the time zone of the city in that clue. (Use the time zone provided, which should account for summer time where in use.)

EXAMPLE: the first letter is H, and the time zone is UTC+12; shifting H forward in the alphabet by 12 gives the letter T.</hint>
			<hint>The solution is TIME FLIES.</hint>
			<solution href="00-location-solution.pdf"/>
		</puzzle>
		<answerword>timeflies</answerword>
	</location>

	<puzzle>
		<title>Tears of a Clown</title>
		<file href="01-tears_of_a_clown.pdf"/>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<solution href="01-tears_of_a_clown-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>History of Dance</title>
		<file href="02-history_of_dance.pdf"/>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<solution href="02-history_of_dance-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Nations of the World</title>
		<file href="03-nations_of_the_world.pdf"/>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<solution href="03-nations_of_the_world-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Beyond Thunderdome</title>
		<file href="04-beyond_thunderdome.pdf"/>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<solution href="04-beyond_thunderdome-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Pick up the Pieces (meta puzzle)</title>
		<file href="05-meta.pdf"/>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Exclamation Pints! (bonus puzzle)</title>
		<file href="06-bonus.pdf"/>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<hint>Hint</hint>
		<solution href="06-bonus-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/archives/2010/09/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../../month.dtd">
<PPMonth>
	<year>2010</year>
	<month>9</month>
	<title>Pirates</title>
	<icon href="icon.png"/>
	<notes>
	</notes>
	<location>
		<puzzle>
			<title>Maps</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>Here is a list of words that you need to find:

- ALONE
- ASHORE
- BELT
- CANAL
- CANNON
- CANOE
- CAPTAIN
- CHEST
- CLIMB
- CROOK
- CURSE
- GRASP
- HORN
- IRON
- JOHNNYDEPP
- LAMP
- LAST
- NEED
- ONCE
- OPENSEAS
- PARROT
- PEGLEG
- PIRATE
- PLANK
- PLOT
- PLUNDER
- PROP
- RACE
- RAGE
- REDBEARD
- ROPE
- SAGA
- SALT
- SCURVY
- STEAL
- TALE
- TIKI
- TIRE
- TREASURE
- VOYAGE</hint>
<hint>Focus on the (few) unused letters in the word search.</hint>
<hint>Does the size of the wordsearch match the size of the maps?</hint>
<hint>Focus on the first letter of each line of the poem.</hint>
			<hint>The solution is JOLLY ROGER</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>jollyroger</answerword>
	</location>
	
	<puzzle>
		<title>One More Day Johnny</title>
		<file href="01-johnny-puzzle.jpg"/>
		<solution href="01-johnny-solution.jpg"/>
	</puzzle>
	
	<puzzle>
		<title>Mirage</title>
		<file href="02-mirage-puzzle.pdf"/>
		<solution href="02-mirage-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Think Like a Pirate</title>
		<file href="03-think_like_a_pirate-puzzle.pdf"/>
		<solution href="03-think_like_a_pirate-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Aftermath</title>
		<file href="04-aftermath-puzzle.pdf"/>
		<solution href="04-aftermath-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Meta/Answersheet</title>
		<file href="05-meta_answersheet-puzzle.pdf"/>
		<solution href="05-meta_answersheet-solution.pdf"/>
	</puzzle>
	
	<answerSheet href="05-meta_answersheet-puzzle.pdf"/>
	<answerSheetSolution href="05-meta_answersheet-solution.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2016/05/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2016</year>
	<month>5</month>
	<title>Parks and Recreation</title>
	<notes>Thanks to Seattle Puzzled Pint player Jonah Ostroff for writing all of this month's puzzles!</notes>
	<location>
		<puzzle>
			<title>Name Trouble</title>
			<file href="00-location-puzzle.pdf"/>
    		<hint>Identify the words and names that rhyme with "Gary".</hint>
    		<hint>Did you find "Fairey" and "Dairy"?</hint>
    		<hint>The words are Fairey, Barry, Harry, Kerry, Dairy, Sherry, Perry, and Mary</hint>
    		<hint>Use the arrows to shift the letters</hint>
            <hint>First letter is "E"</hint>
            <hint>The solution is EAGLETON</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>eagleton</answerword>
	</location>

	<puzzle>
		<title>Treat Yo Self!</title>
		<file href="01-treat_yo_self-puzzle.pdf"/>
		<solution href="01-treat_yo_self-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Cones of Dunshire</title>
		<file href="02-cones_of_dunshire-puzzle.pdf"/>
		<solution href="02-cones_of_dunshire-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Burt Macklin: FBI</title>
		<file href="03-burt_macklin_fbi-puzzle.pdf"/>
		<solution href="03-burt_macklin_fbi-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Food and Stuff</title>
		<file href="04-food_and_stuff-puzzle.pdf"/>
		<solution href="04-food_and_stuff-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>A Pit Into a Park (meta puzzle)</title>
		<file href="05-pit_into_a_park-puzzle.pdf"/>
		<solution href="05-pit_into_a_park-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Entertainment 720</title>
		<file href="06-entertainment_720-puzzle.pdf"/>
		<solution href="06-entertainment_720-solution.pdf"/>
	</puzzle>

	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/archives/2015/09/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2015</year>
	<month>10</month>
	<title>Doctor Who</title>
	<icon href="icon.png"/>
	<notes>You need a bit of Doctor Who knowledge to solve some of these puzzles, but we provide it for you.  Doctor and Companion bios are sprinkled around all the puzzle pages and answer sheet. Some will be useful in solving certain puzzles...

Like August, September's event was a bit more technological than most: It used [ClueKeeper](http://www.cluekeeper.com/) to help host the hunt.  Players had the option to use ClueKeeper (in addition to our normal Game Control hosts) to track puzzle progress and get hints.  This ClueKeeper hunt is still available, if you'd like to use it - Download the app and get the hunt using code `PPSEP15`.  Alternatively, the puzzles as presented below can be used independent of the app.

To fully understand a puzzle's solution, read the hints as well.

Thanks to the Austin Puzzled Pint organizers for writing all of this month's puzzles!</notes>
	<location>
		<puzzle>
			<title>TARDIS Navigation Console</title>
			<file href="00-tardis_navigation_console-puzzle.pdf"/>
			<hint>So London was called "The Big Smoke"... can you think of nicknames for any other Puzzled Pint cities? Do the images on the dials help?

	(Check our [About page](http://www.puzzledpint.com/about/) for a current list of cities.)</hint>
			<hint>Having trouble with city nicknames? Try [searching](http://www.google.com/) for `[PP CITY] nicknames` or `[IMAGE] city nickname`.

	(Check our [About page](http://www.puzzledpint.com/about/) for a current list of cities.)

	_The next hint will tell you the names of all the images._</hint>
			<hint>The dial images are (top to bottom, left to right):

	- Jet
	- Cream
	- Wind
	- Bean
	- Saint Nick &amp; Saint Bernard
	- Apple
	- Iron
	- Angels
	- Sun over a valley
	- Golden Gate
	- Rose
	- Hog
	- Bat

	Do any of those words remind you of nicknames for Puzzled Pint cities? Have you tried searching for `[IMAGE] city nickname`?

	_The next hint will tell you what all the cities are._</hint>		
			<hint>The cities are (top to bottom, left to right):

	- Seattle
	- Milwaukee
	- Chicago
	- Boston
	- Montreal
	- New York
	- Pittsburgh
	- Los Angeles
	- Phoenix
	- San Francisco
	- Portland
	- Toronto
	- Austin

	Now, what could the number on each dial be telling you to do?</hint>
			<hint>Solution displayed to the player</hint>
			<hint>Take the first letter of each city and modify it by the number shown on the dial to get a new letter.

	For example, the first dial indicates Seattle (Jet City) and the dial shows +1, so S+1=T.</hint>
			<solution>Go meet The Doctor at... "THE CLOSEST PUB".</solution>
		</puzzle>
		<answerword>theclosestpub</answerword>
	</location>
	
	<puzzle>
		<title>Familiar Faces</title>
		<file href="01-familiar_faces-puzzle.pdf"/>

		<hint>Each set of answer blanks will be the name of a famous actor or actress.  Famous means IMDB top 100 of all time</hint>
		<hint>There is a movie in the collection at the bottom for each actor or actress</hint>
		<hint>Each real name (or part of a name) is obscured in the puzzle by a related word like a synonym, e.g. Harri=Badger, son=child, Ford=Cross</hint>
		<hint>Also consider homophones like "Right and Wright"</hint>
		<hint>Also consider similar things like "Lem(m)on and Lime"</hint>
		<hint>Also consider instances of things like "Fawkes and Phoenix"</hint>
		<hint>The actors and actresses, in order, are Jack Lemmon, Nic Cage, Peter Sellers, Harrison Ford, Heath Ledger, Cary Grant, River Phoenix, Robin Wright, John Hurt, Brad Pitt</hint>
		<solution>Putting the names in place, you get "Melody Pond". Applying the rule one more time gives you "RIVER SONG", the name of the Doctor's wife.  SPOILERS!</solution>
	</puzzle>
	
	<puzzle>
		<title>I've got an Ood feeling about this...</title>
		<file href="02-got_an_ood_feeling-puzzle.pdf"/>
		<hint>You need to pay attention to only some of the numbered circles, but which ones? </hint>
		<hint>Try looking at only the Ood ones (odd numbered circles) </hint>
		<hint>"can't see" the solution?  Are you blind?</hint>
		<hint>They form four rows of Braille </hint>
		<hint>The last row doesn't code right. Perhaps the lines so far and/or the flavor text could help? What is the "Angle of Incidence"?</hint>
		<hint>The Braille on the last line is reflected along the vertical axis</hint>
		<solution>REFLECT / UPON THE / DANGERS / VAMPIRE (mirrored Braille)</solution>
	</puzzle>
	
	<puzzle>
		<title>Bad Wolf</title>
		<file href="03-bad_wolf-puzzle.pdf"/>
		<hint>There's an important # you get to get out of the flavor text.  It'll help you find the answers to the clues</hint>
		<hint>Each answer will be exactly seven letters (The number of letters in BadWolf, The 7 seas, the 7 muses, and the 7 deadly sins)</hint>
		<hint>Notice the first letters of each clue spell out "Bad Wolf" in each column..</hint>
		<hint>Each answer will also start with the letters from Bad Wolf</hint>
		<hint>The answers to the clues are: Baptist, Azimuth, Dictate, Weekend, Orlando, Laconic, Fastest, Buffalo, Another, Detours, WH Smith, Oregano, Legroom, Frisbee</hint>
		<hint>You've looked at the first letter of each answer.  Perhaps look at a different letter?</hint>
		<solution>The last letters spell "The Doctor's Home" which is GALLIFREY, as found on the reference sheet</solution>
	</puzzle>
	
	<puzzle>
		<title>Time Loops</title>
		<file href="04-time_loops-puzzle.pdf"/>
		<hint>You are going to need your code sheet for this one </hint>
		<hint>The flavor text keywords to notice: "Organize" "Parallel".  </hint>
		<hint>You have to view the loops side-by-side</hint>
		<hint>Rotate the loops until they match up TARDIS with TARDIS and Dalek with Dalek and number with number</hint>
		<hint>The dots on the Daleks are Braille </hint>
		<hint>Each TARDIS is one of the two semaphore flag pairs </hint>
		<hint>You need to read both sides of each loop </hint>
		<hint>The Daleks' message is "SUBTRACT NINETY" </hint>
		<hint>The Doctor's message is "REPAIR LOOPS" </hint>
		<hint>The Dalek's message is telling you how to interpret the numbers. Subtract ninety from each then look up the decimal letter on the code sheet </hint>
		<hint>The Doctor's message is telling you that you now need to recombine the two loops into one loop. </hint>
		<hint>If you put the loops together correctly, the numbers spell out "MORSE CODE" on one side and "WRONG SIDE" on the other side. </hint>
		<hint>This is telling you to read the loop one more time but decoding morse code with every TARDIS a Dash and every Dalek a Dot (A Dalek is a single Dot regardless of the number of Braille dots on its chassis). Numbers separate morse letters. Only one side will decode correctly, the "WRONG SIDE" won't</hint>
		<solution>"PERI BROWN", one of the Doctor's companions as listed on the reference sheet</solution>
	</puzzle>
	
	<puzzle>
		<title>Who am I? (Meta)</title>
		<file href="05-who_am_i-puzzle.pdf"/>
		<hint>The answers to these 20 questions will clue you to the meta puzzle answer by describing it. But what are the answers? </hint>
		<hint>Answer each question using the puzzle answer from the puzzle specified in the first column. For example, Answer 1 is "Yes" because River Song grows and breathes</hint>
		<hint>Use the reference material provided to help answer the questions</hint>
		<hint>There are four indicated letters at the bottom, find those four letters using the five questions answers for each puzzle. </hint>
		<hint>This is done via a binary translation to find the letters, yes is 1. </hint>
		<hint>The answers to the questions are FF->Y,N,N,Y,N=R / OF->N,N,Y,N,Y=E / BW->N,N,Y,Y,Y=G / TL->N,Y,Y,Y,Y=O</hint>
		<hint>Now play normal 20 questions and try to figure out the answer as if ALL these 20 questions were all being asked about the meta's answer</hint>
		<hint>To summarize.  A fictional character from Earth born a long time ago, often in a castle, which has a place of authority which is round, who is not a wizard, but is a warrior noble.  someone sacrificed thier life for him or her and he or she has a friend with extraordinary abilities</hint>
		<hint>The first word is KING.  Know any fictional kings from old stories?</hint>
		<solution>The 20 questions describe "KING ARTHUR PENDRAGON"</solution>
	</puzzle>
	
	<puzzle>
		<title>Back to the Future (bonus puzzle)</title>
		<file href="06-back_to_the_future-puzzle.pdf"/>
		<hint>```(2+3) = DEADLINE 
		(2+5) = BANTERED
		(2+11) = AMENDED
		(5+7) = WATERBED
		(7+8) = WHEEDLED
		(11+12) = DRUMBEAT```</hint>
		<hint>```(3) = DIAL
		(4) = LID
		(5) = BRAT
		(6) = BAR
		(7) = WEED
		(8) = HELD
		(9) = LED
		(10) = WED
		(11) = MAD
		(12) = BRUTE
		(13) = TUBE
		(14) = RUBE
		(15) = MAID
		(16) = AD
		(17) = DEN```</hint>
		<solution>FATHER TIME</solution>
	</puzzle>
	
	<allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2015/02/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2015</year>
	<month>2</month>
	<title>Phobias</title>
	<notes>Thanks to the [Chicago Puzzled Pint](https://twitter.com/puzzpintchi) organizers for writing all of this month's puzzles!</notes>
	<location>
		<puzzle>
			<title>Mazeophobia</title>
			<file href="00-location-puzzle.pdf"/>
			<hint>Read the directions.</hint>
			<hint>Read the directions can have two different meanings.</hint>
			<hint>Within each paragraph there are words that might indicate the direction to travel.</hint>
			<hint>Not sure where to begin? What letter seems to stick out in the directions?</hint>
			<hint>Read the directions and follow the path on the maze as indicated by the directions starting with R. 

Direction words:

- Above
- Beneath
- Down
- Left
- Ported
- Reverse
- Right
- Top
- Underneath
- Up</hint>
			<hint>Got a message from the maze?  Not sure what to do next?  [This website](http://www.rot-n.com/) may help.</hint>
			<hint>Solution displayed to the player</hint>
            <hint>The solution word is UNFOUNDED.</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>unfounded</answerword>
	</location>
	
	<puzzle>
		<title>Chorophobia</title>
		<file href="01-chorophobia-puzzle.pdf"/>
		<solution href="01-chorophobia-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Cynophobia</title>
		<file href="02-cynophobia-puzzle.pdf"/>
		<solution href="02-cynophobia-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Neophobia</title>
		<file href="03-neophobia-puzzle.pdf"/>
		<solution href="03-neophobia-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Sarmassophobia</title>
		<file href="04-sarmassophobia-puzzle.pdf"/>
		<solution href="04-sarmassophobia-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Panphobia (meta puzzle)</title>
		<file href="05-panphobia-puzzle.pdf"/>
        <hint>The 8 hints in parentheses are short words, and the 8 definitions below are longer.</hint>
        <hint>The solution to the top words are embedded in the solution to the bottom words</hint>
        <hint>- Canine = DOG
- Site = PLACE
- Rod = BAR
- Corn Holder = COB

- A person may do this on eBay = BID
- Not a he or she = IT
- Portrayer = ACTOR
- Not you = ME

- Religious principles = DOGMA
- Type of snake = COBRA
- Extreme support = RABID
- Carrier of cargo = BARGE

- Leave out = OMIT
- Disease caused by insects = LYME
- Home of nuclear energy = REACTOR
- Harmless substance = PLACEBO</hint>
        <hint>Insert the 4 meta answers into the slots so the parenthetical words + the adjacent
two letters from the answer spell out one of the defined words from below. The
letters that remain (from the middle of the 4 answer words) will spell SCARED
STUPID.</hint>
		<solution href="05-panphobia-solution.jpg"/>
	</puzzle>
	
	<puzzle>
		<title>Mottephobia (bonus puzzle)</title>
		<file href="06-mottephobia-puzzle.pdf"/>
		<solution href="06-mottephobia-solution.pdf"/>
	</puzzle>
	
    <allPuzzles href="allpuzzles.pdf"/>
	<answerSheet href="answersheet.pdf"/>
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2011/02/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2011</year>
	<month>2</month>
	<title>(no theme)</title>
	<icon href="icon.png"/>
	<location>
		<puzzle>
			<title>Pickup Lines</title>
			<file href="00-location-puzzle.txt"/>
			<hint>Maybe the right combinations will add up to something that makes sense...</hint>
			<hint>Shifting a LETTER forward in the alphabet by a certain NUMBER will yield a new letter.</hint>
			<hint>"Do you believe in love at first sight?" (F) + "Or do you want me to walk by again?" (6) = L</hint>		
			<hint>Hint 4</hint>
			<hint>Solution displayed to the player</hint>
			<solution href="00-location-solution.html" />
		</puzzle>
		<answerword>luckylabse</answerword>
	</location>
	
	<puzzle>
		<title>Gifts</title>
		<file href="01-gifts-puzzle.pdf"/>
		<solution href="01-gifts-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Transportation</title>
		<file href="02-transportation-puzzle.pdf"/>
		<solution href="02-transportation-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>Dinner</title>
		<file href="03-dinner-puzzle.pdf"/>
		<solution href="03-dinner-solution.pdf"/>
	</puzzle>
	
	<puzzle>
		<title>A Movie</title>
		<file href="04-a_movie-puzzle.pdf"/>
		<solution href="04-a_movie-solution.doc"/>
	</puzzle>
	
	<puzzle>
		<title>Meta</title>
		<file href="05-meta-puzzle.pdf"/>
		<solution href="05-meta-solution.pdf"/>
	</puzzle>
	
</PPMonth>

=== BrianEnigma/puzzled_pint_archives/2013/11/month.xml
<?xml version="1.0" ?>
<!DOCTYPE PPMonth SYSTEM "../../month.dtd">
<PPMonth>
	<year>2013</year>
	<month>11</month>
	<title>The Five Senses</title>
	<notes>
	</notes>
	<location>
		<puzzle>
			<title>Sound</title>
			<file href="00-location-puzzle.mp3"/>
			<hint>These are quotations from the American television show The X-Files.</hint>
			<hint>You might find [this Wikiquote page](https://en.wikiquote.org/wiki/The_X-Files) and [this fan site](http://www.insidethex.co.uk/#one) helpful.</hint>
			<hint>Use the first letter of each word that is bleeped out to discover: "What does Fox say?"</hint>
			<hint>The solution is: STRATEGO</hint>
			<solution href="00-location-solution.pdf" />
		</puzzle>
		<answerword>stratego</answerword>
	</location>

	<puzzle>
		<title>Scent</title>
		<file href="01-scent-puzzle.pdf"/>
		<solution href="01-scent-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Sight</title>
		<file href="02-sight-puzzle.pdf"/>
		<solution href="02-sight-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Taste</title>
		<file href="03-taste-puzzle.pdf"/>
		<solution href="03-taste-solution.pdf"/>
	</puzzle>

	<puzzle>
		<title>Touch</title>
		<file href="04-touch-puzzle.pdf"/>
        <hint href="04-touch-hints.pdf"/>
		<solution href="04-touch-solution.pdf"/>
	</puzzle>
</PPMonth>
